apiVersion: apps/v1
kind: Deployment
metadata:
  name: $(APP_NAME)
  namespace: $(NAMESPACE)
  labels:
    app: $(APP_NAME)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $(APP_NAME)
  template:
    metadata:
      labels:
        app: $(APP_NAME)
    spec:
      containers:
        - name: echo-message
          image: busybox:1.36
          command: ["/bin/sh", "-c"]
          args:
            - while true; do echo "Hello from $(APP_NAME)! $(date)"; sleep 5; done
          env:
            - name: APP_NAME
              value: $(APP_NAME)
