apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  
images:
- name: busybox
  newName: busybox
  newTag: "1.36"

patchesStrategicMerge:
  - patch-resources.yaml

  