apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - subscription.yaml

# patches:
# - target:
#     kind: ClusterServiceVersion
#     name: grafana-operator.v5.19.4
#   patch: |
#     - op: replace 
#       path: /spec/relatedImages/1/image
#       value: quay.io/grafana-operator/grafana-operator:v5.19.4
#     - op: replace
#       path: /spec/install/spec/deployments/0/spec/template/spec/containers/0/image
#       value: quay.io/grafana-operator/grafana-operator:v5.19.4
    