apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

replacements:
- source:
    fieldPath: metadata.name
    kind: ConfigMap
    name: ent-alertiis-im-all-httpout-int
  targets:
  - fieldPaths:
    - metadata.name
    - metadata.labels.app
    - spec.selector.matchLabels.app
    - spec.template.spec.containers.0.env.0.value
    - spec.template.metadata.labels.app
    select:
      kind: Deployment
- source:
    fieldPath: metadata.namespace
    kind: ConfigMap
    name: ent-alertiis-im-all-httpout-int
  targets:
  - fieldPaths:
    - metadata.namespace
    select:
      kind: Deployment
