apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: broker
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - deleteClaim: false
        id: 0
        size: 100Gi
        type: persistent-claim