apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: controller
spec:
  replicas: 3
  roles:
    - controller
  resources:
    limits:
        cpu: '1'
        memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi
  storage:
    type: jbod
    volumes:
      - deleteClaim: false
        id: 0
        size: 100Gi
        type: persistent-claim
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: Exists
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    strimzi.io/pool-name: broker
                topologyKey: kubernetes.io/hostname
              weight: 100
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              strimzi.io/pool-name: broker
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway