apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: KafkaNodePool
      name: broker
    patch: |-
      - op: replace
        path: /spec/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/resources/limits/cpu
        value: 2
      - op: replace
        path: /spec/resources/requests/memory
        value: 1Gi
      - op: replace
        path: /spec/resources/limits/memory
        value: 2Gi
