apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olm-operators
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-operators
  source:
    repoURL: https://github.com/dmak84/kafka-demo.git
    targetRevision: main
    path: manifests/olm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true