apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-qa
  namespace: openshift-gitops
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-qa
  source:
    repoURL: https://github.com/dmak84/kafka-demo.git
    targetRevision: main
    path: manifests/kafka/overlays/qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true